// Generated by BUCKLESCRIPT VERSION 2.2.2, PLEASE EDIT WITH CARE
'use strict';

var JsSha256 = require("js-sha256");
var Pervasives = require("bs-platform/lib/js/pervasives.js");

function createHash(index, currentTime, data, previousHash) {
  return JsSha256.sha256(Pervasives.string_of_int(index) + (Pervasives.string_of_float(currentTime) + (data + previousHash)));
}

function blockBuilder(index, previousHash) {
  var currentTime = Date.now();
  var data = "Hey! I'm block " + Pervasives.string_of_int(index);
  var hash = createHash(index, currentTime, data, previousHash);
  return /* record */[
          /* index */index,
          /* timestamp */currentTime,
          /* data */data,
          /* previousHash */previousHash,
          /* hash */hash
        ];
}

function createGenesisBlock() {
  return blockBuilder(0, "0");
}

function nextBlock(lastBlock) {
  var newIndex = lastBlock[/* index */0] + 1 | 0;
  return blockBuilder(newIndex, lastBlock[/* hash */4]);
}

exports.createHash = createHash;
exports.blockBuilder = blockBuilder;
exports.createGenesisBlock = createGenesisBlock;
exports.nextBlock = nextBlock;
/* js-sha256 Not a pure module */
